name: Weekly Current-Week Card

on:
  workflow_dispatch:   # allows manual run
  schedule:
    - cron: "0 13 * * 1"   # every Monday at 9 AM EST

jobs:
  screenshot-and-post:
    runs-on: ubuntu-latest
    steps:
      - name: Take screenshot with ScreenshotAPI
        run: |
          curl -X GET "https://shot.screenshotapi.net/screenshot" \
            -G \
            --data-urlencode "token=T228CKG-Y5Y464H-PT0JKH8-0HGM4HQ" \
            --data-urlencode "url=https://bryceas44.github.io/physical-program/" \
            --data-urlencode "output=image" \
            --data-urlencode "file_type=png" \
            --data-urlencode "start_date=2025-08-18" \
            -o card.png

      - name: Post to Discord
        run: |
          curl -X POST -H "Content-Type: multipart/form-data" \
            -F "file1=@card.png" \
            ${{ secrets.DISCORD_WEBHOOK }}
