name: Weekly Current-Week Card (Playwright)

on:
  schedule:
    - cron: "0 14 * * 1"   # Every Monday 14:00 UTC
  workflow_dispatch:

jobs:
  shoot-week-card:
    runs-on: ubuntu-latest
    env:
      START_DATE: "2025-08-18"
      BASE_URL: "https://bryceas44.github.io/physical-program/"
    steps:
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Playwright Chromium
        run: |
          npm i -g playwright@1
          playwright install --with-deps chromium

      - name: Compute current week number 1–16
        id: calc
        run: |
          start=$(date -u -d "$START_DATE" +%s)
          today=$(date -u +%s)
          diff=$(( (today - start) / 86400 ))
          week=$(( diff / 7 + 1 ))
          if [ $week -lt 1 ]; then week=1; fi
          if [ $week -gt 16 ]; then week=16; fi
          echo "week=$week" >> $GITHUB_OUTPUT
          echo "Computed week: $week"

      - name: Screenshot the week card
        env:
          WEEK: ${{ steps.calc.outputs.week }}
          URL:  ${{ env.BASE_URL }}
        run: |
          node - <<'JS'
          const { chromium } = require('playwright');
          (async () => {
            const week = process.env.WEEK;
            const url  = process.env.URL;
            const sel  = `#week-${week}`;

            const browser = await chromium.launch();
            const ctx = await browser.newContext({
              viewport: { width: 1440, height: 2200 },
              deviceScaleFactor: 2,
            });
            const page = await ctx.newPage();

            await page.goto(url, { waitUntil: 'networkidle' });
            await page.waitForTimeout(3000);
            const el = await page.$(sel);
            if (!el) throw new Error(`Selector not found: ${sel}`);

            await el.scrollIntoViewIfNeeded();
            await el.screenshot({ path: `week-${week}.png` });

            await browser.close();
          })().catch(e => { console.error(e); process.exit(1); });
          JS

      - name: Post PNG to Discord
        run: |
          curl -F "file1=@week-${{ steps.calc.outputs.week }}.png" \
               -F "payload_json={\"content\":\"Week ${{ steps.calc.outputs.week }} ✅\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}

      - name: Upload artifact (debug/verify)
        uses: actions/upload-artifact@v4
        with:
          name: week-${{ steps.calc.outputs.week }}.png
          path: week-${{ steps.calc.outputs.week }}.png
          retention-days: 7
